### ISSUE TITLE
More link types?

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [httpreserve/tikalinkextract#6]
Hi!
I'm using the windows binary 64-bit release from here:
https://github.com/httpreserve/tikalinkextract/releases/tag/0.0.2

It works great .However I have more link types that I want to find, for example pw://ProjectWise.ProjectWise.com

Is it possible to add more link types to look for?  Maybe by providing a CLI option that points to a file with additional file types to look for?

**Comment by ross-spencer** [comment]
That sounds great Kristian! I can look at this at the weekend. Some sort of external configuration would be perfect. Glad you're finding the utility handy!

**Comment by ross-spencer** [comment]
Sorry about the time taken to address this @kristiansvenssonwsp but let me know if today's release will help in your workflow: https://github.com/httpreserve/tikalinkextract/releases/tag/tle-0.0.3. Thanks for the feature suggestion.
